const { describe, it } = require('node:test');
const { equal: eq, deepEqual: deq, ok } = require('node:assert');
const { getTableConfig } = require('drizzle-orm/pg-core');
const { lettingStatus, ...parkTables } = require('./lib/park-schema');

const columnTypesByKind = {
  Integer: ['PgInteger', 'PgSmallInt', 'PgSerial', 'PgSmallSerial'],
  BigInt: ['PgBigInt53', 'PgBigInt64', 'PgBigSerial53', 'PgBigSerial64'],
  Decimal: ['PgNumeric', 'PgNumericNumber', 'PgNumericBigInt'],
  Real: ['PgReal', 'PgDoublePrecision'],
  Text: ['PgVarchar', 'PgChar', 'PgText'],
  Boolean: ['PgBoolean'],
  Uuid: ['PgUUID'],
  Date: ['PgDate', 'PgDateString'],
  Timestamp: ['PgTimestamp', 'PgTimestampString'],
  Time: ['PgTime'],
  Json: ['PgJson', 'PgJsonb'],
  Enum: ['PgEnumColumn'],
};

const configOf = (key) => getTableConfig(parkTables[key]);

const columnsOf = (key) => configOf(key).columns;

const columnNamed = (key, name) => columnsOf(key).find((column) => column.name === name);

const everyColumn = Object.keys(parkTables).flatMap(columnsOf);

const referencesOf = (key) => configOf(key).foreignKeys.map((foreignKey) => foreignKey.reference());

const referenceSummary = (reference) => ({
  columns: reference.columns.map((column) => column.name),
  foreignTable: getTableConfig(reference.foreignTable).name,
  foreignColumns: reference.foreignColumns.map((column) => column.name),
});

describe('park schema fixture', () => {
  describe('column kinds', () => {
    for (const [kind, columnTypes] of Object.entries(columnTypesByKind)) {
      it(`includes at least one ${kind} column`, () => {
        const covering = everyColumn.filter((column) => columnTypes.includes(column.columnType));
        ok(covering.length > 0, `no column of kind ${kind}; expected one of ${columnTypes.join(', ')}`);
      });
    }
  });

  describe('primary keys', () => {
    it('generates park ids with GENERATED ALWAYS AS IDENTITY', () => {
      deq(columnNamed('parks', 'id').generatedIdentity, { type: 'always' });
    });

    it('generates accessory ids with GENERATED BY DEFAULT AS IDENTITY', () => {
      deq(columnNamed('accessories', 'id').generatedIdentity, { type: 'byDefault' });
    });

    it('generates pitch ids from a serial sequence', () => {
      eq(columnNamed('pitches', 'id').columnType, 'PgSerial');
    });

    it('generates holiday home ids from a bigserial sequence', () => {
      eq(columnNamed('holidayHomes', 'id').columnType, 'PgBigSerial53');
    });

    it('identifies owners by uuid', () => {
      eq(columnNamed('owners', 'id').columnType, 'PgUUID');
    });

    it('identifies park owners by a composite primary key', () => {
      deq(
        configOf('parkOwners').primaryKeys.map((primaryKey) => primaryKey.columns.map((column) => column.name)),
        [['park_id', 'owner_id']],
      );
    });
  });

  describe('relationships', () => {
    it('refers a pitch to its park', () => {
      deq(referencesOf('pitches').map(referenceSummary), [
        { columns: ['park_id'], foreignTable: 'parks', foreignColumns: ['id'] },
      ]);
    });

    it('refers an owner to the owner who referred them', () => {
      deq(referencesOf('owners').map(referenceSummary), [
        { columns: ['referred_by_owner_id'], foreignTable: 'owners', foreignColumns: ['id'] },
      ]);
      eq(columnNamed('owners', 'referred_by_owner_id').notNull, false);
    });

    it('refers a holiday home to its pitch, its owner and its previous owner', () => {
      deq(referencesOf('holidayHomes').map(referenceSummary), [
        { columns: ['pitch_id'], foreignTable: 'pitches', foreignColumns: ['id'] },
        { columns: ['owner_id'], foreignTable: 'owners', foreignColumns: ['id'] },
        { columns: ['previous_owner_id'], foreignTable: 'owners', foreignColumns: ['id'] },
      ]);
      eq(columnNamed('holidayHomes', 'previous_owner_id').notNull, false);
    });

    it('refers a park owner to both its park and its owner', () => {
      deq(referencesOf('parkOwners').map(referenceSummary), [
        { columns: ['park_id'], foreignTable: 'parks', foreignColumns: ['id'] },
        { columns: ['owner_id'], foreignTable: 'owners', foreignColumns: ['id'] },
      ]);
    });
  });

  describe('unique constraints', () => {
    it('constrains lettings to one per holiday home and start date', () => {
      deq(
        configOf('lettings').uniqueConstraints.map((constraint) => [
          constraint.name,
          constraint.columns.map((column) => column.name),
        ]),
        [['lettings_holiday_home_id_start_date_key', ['holiday_home_id', 'start_date']]],
      );
    });

    it('constrains owners to one per email address', () => {
      eq(columnNamed('owners', 'email').isUnique, true);
    });
  });

  describe('enums', () => {
    it('declares the letting status enum', () => {
      eq(lettingStatus.enumName, 'letting_status');
      deq(lettingStatus.enumValues, ['pending', 'confirmed', 'cancelled']);
      eq(columnNamed('lettings', 'status').columnType, 'PgEnumColumn');
    });
  });

  describe('nullability and defaults', () => {
    it('includes nullable columns', () => {
      const nullable = everyColumn.filter((column) => !column.notNull).map((column) => column.name);
      deq(nullable, [
        'latitude',
        'amenities',
        'facilities',
        'warden_id',
        'area_sqm',
        'referred_by_owner_id',
        'previous_owner_id',
        'purchase_price',
        'specification',
        'inspected_at',
        'notes',
      ]);
    });

    it('includes columns with database defaults beyond the generated keys', () => {
      const defaulted = everyColumn
        .filter((column) => column.hasDefault && !column.primary)
        .map((column) => column.name);
      deq(defaulted, ['active', 'created_at', 'has_electricity', 'loyalty_points', 'quantity', 'status']);
    });
  });
});
