const { describe, it } = require('node:test');
const { deepEqual: deq, equal: eq, ok, rejects } = require('node:assert');
const { createRowBatchSink, generate } = require('../lib');
const { structuralParkRules } = require('./lib/park-rules');
const parkSchema = require('./lib/park-schema');

const SEED = 42;
const REFERENCE_DATE = new Date('2024-06-01T00:00:00.000Z');

const COUNTS = {
  parks: 3,
  pitches: 5,
  owners: 6,
  holidayHomes: 4,
  accessories: 3,
  lettings: 5,
  parkOwners: 3,
};

const generateBatches = (handler, overrides = {}) =>
  generate(
    {
      schema: parkSchema,
      rules: structuralParkRules,
      counts: COUNTS,
      seed: SEED,
      referenceDate: REFERENCE_DATE,
      ...overrides,
    },
    createRowBatchSink(handler),
  );

const collectBatches = async (overrides = {}) => {
  const batches = [];
  const report = await generateBatches((batch) => batches.push(batch), overrides);
  return { batches, report };
};

describe('row batch sink', () => {
  describe('the batches it delivers', () => {
    it('carries the table key, the drizzle table and the rows', async () => {
      const { batches } = await collectBatches({ counts: { parks: 2 } });

      eq(batches.length, 1);
      eq(batches[0].tableKey, 'parks');
      eq(batches[0].table, parkSchema.parks);
      eq(batches[0].rows.length, 2);
      deq(Object.keys(batches[0].rows[0]), [
        'id',
        'name',
        'region',
        'openedAt',
        'latitude',
        'amenities',
        'facilities',
        'active',
        'createdAt',
        'wardenId',
      ]);
    });

    it('delivers the tables in dependency order', async () => {
      const { batches } = await collectBatches();

      deq(
        [...new Set(batches.map((batch) => batch.tableKey))],
        ['owners', 'parks', 'pitches', 'holidayHomes', 'accessories', 'lettings', 'parkOwners'],
      );
    });

    it('never exceeds the batch size', async () => {
      const { batches } = await collectBatches({ batchSize: 2 });

      ok(batches.every((batch) => batch.rows.length <= 2));
      deq(
        batches.filter((batch) => batch.tableKey === 'owners').map((batch) => batch.rows.length),
        [2, 2, 2],
      );
    });

    it('finishes each table before starting the next', async () => {
      const { batches } = await collectBatches({ batchSize: 2 });
      const tableKeys = batches.map((batch) => batch.tableKey);

      deq(
        tableKeys,
        [...tableKeys].sort((a, b) => tableKeys.indexOf(a) - tableKeys.indexOf(b)),
      );
    });

    it('delivers no batch for a table counted at zero', async () => {
      const { batches, report } = await collectBatches({ counts: { parks: 0, pitches: 0 } });

      deq(batches, []);
      deq(report.rowCounts, { parks: 0, pitches: 0 });
    });

    it('returns the generation report from end', async () => {
      const { report } = await collectBatches();

      eq(report.seed, SEED);
      eq(report.referenceDate, REFERENCE_DATE);
      deq(report.rowCounts, COUNTS);
    });
  });

  describe('overriding the system value', () => {
    const overrideFlags = async () => {
      const { batches } = await collectBatches();
      return new Map(batches.map((batch) => [batch.tableKey, batch.overrideSystemValue]));
    };

    it('is set for exactly the tables with a generated always identity column', async () => {
      deq([...(await overrideFlags())].sort(), [
        ['accessories', false],
        ['holidayHomes', false],
        ['lettings', true],
        ['owners', false],
        ['parkOwners', false],
        ['parks', true],
        ['pitches', false],
      ]);
    });

    it('is not set for a generated by default identity column', async () => {
      eq((await overrideFlags()).get('accessories'), false);
    });

    it('is not set for a serial column', async () => {
      eq((await overrideFlags()).get('pitches'), false);
    });
  });

  describe('sequencing', () => {
    it('awaits each batch before generating the next', async () => {
      const events = [];
      await generateBatches(
        async (batch) => {
          events.push(`start ${batch.tableKey} ${batch.rows[0].id}`);
          await Promise.resolve();
          events.push(`end ${batch.tableKey} ${batch.rows[0].id}`);
        },
        {
          counts: { parks: 3 },
          batchSize: 1,
        },
      );

      deq(events, ['start parks 1', 'end parks 1', 'start parks 2', 'end parks 2', 'start parks 3', 'end parks 3']);
    });
  });

  describe('a handler which fails', () => {
    it('aborts the run and propagates the error unwrapped', async () => {
      const failure = new Error('the database said no');
      const seen = [];

      await rejects(
        generateBatches((batch) => {
          seen.push(batch.tableKey);
          if (batch.tableKey === 'pitches') throw failure;
        }),
        (error) => error === failure,
      );

      deq(seen, ['owners', 'parks', 'pitches']);
    });

    it('propagates a rejected promise unwrapped', async () => {
      const failure = new Error('the connection dropped');

      await rejects(
        generateBatches(async () => {
          throw failure;
        }),
        (error) => error === failure,
      );
    });
  });
});
