// Generated by scripts/build-rules.ts: a structuralDefaults skeleton for all 372
// tables, with overrides wherever a check constraint, unique text column or special row
// demands judgment. Regenerate rather than edit.
import {
  type SchemaRules,
  derive,
  pickFrom,
  randomInteger,
  randomWords,
  sequence,
  structuralDefaults,
} from 'drizzle-super-seed';
import type * as schema from './schema.ts';

const atLeast = (minimum: number) => derive((_row, context) => context.rowIndex + minimum);

const uniqueText = (label: string) => sequence((i) => `${label} ${i + 1}`);

const base26 = (value: number, width: number) => {
  let rest = value;
  let out = '';
  for (let i = 0; i < width; i++) {
    out = String.fromCharCode(97 + (rest % 26)) + out;
    rest = Math.floor(rest / 26);
  }
  return out;
};

const iswcCode = (index: number) => {
  const digits = String(index + 1).padStart(9, '0');
  return `T-${digits.slice(0, 3)}.${digits.slice(3, 6)}.${digits.slice(6, 9)}-0`;
};

export const rules = {
  alternativeMediumInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
  },
  alternativeMediumTrackInMusicbrainz: {
    [structuralDefaults]: true,
  },
  alternativeReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
  },
  alternativeReleaseTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  alternativeTrackInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
  },
  annotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  applicationInMusicbrainz: {
    [structuralDefaults]: true,
    oauthId: uniqueText('oauthId'),
  },
  areaAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  areaAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    areaAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    areaAttributeTypeAllowedValue: null,
  },
  areaAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaContainmentInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    ended: false,
    comment: randomWords({ minLength: 3, maxLength: 30 }),
  },
  areaTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  areaTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  artistAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    artistAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    artistAttributeTypeAllowedValue: null,
  },
  artistAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistCreditGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistCreditInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  artistCreditNameInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
  },
  artistGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    type: derive((_r, c) => (c.rowIndex === 0 ? 3 : c.random.intBetween(1, 5))),
    area: null,
    gender: null,
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    ended: false,
    beginArea: null,
    endArea: null,
  },
  artistIpiInMusicbrainz: {
    [structuralDefaults]: true,
    ipi: sequence((i) => String(10000000000 + i)),
    editsPending: atLeast(0),
  },
  artistIsniInMusicbrainz: {
    [structuralDefaults]: true,
    isni: sequence((i) => String(1000000000000000 + i)),
    editsPending: atLeast(0),
  },
  artistMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  artistRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  artistReleaseGroupNonvaInMusicbrainz: {
    [structuralDefaults]: true,
    isTrackArtist: false,
  },
  artistReleaseGroupPendingUpdateInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistReleaseGroupVaInMusicbrainz: {
    [structuralDefaults]: true,
    isTrackArtist: true,
  },
  artistReleaseNonvaInMusicbrainz: {
    [structuralDefaults]: true,
    isTrackArtist: false,
  },
  artistReleasePendingUpdateInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistReleaseVaInMusicbrainz: {
    [structuralDefaults]: true,
    isTrackArtist: true,
  },
  artistTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  artistTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  autoeditorElectionInMusicbrainz: {
    [structuralDefaults]: true,
    status: pickFrom([1, 2, 3, 4, 5, 6]),
  },
  autoeditorElectionVoteInMusicbrainz: {
    [structuralDefaults]: true,
    vote: pickFrom([-1, 0, 1]),
  },
  cdtocInMusicbrainz: {
    [structuralDefaults]: true,
    discid: uniqueText('discid'),
  },
  cdtocRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  countryAreaInMusicbrainz: {
    [structuralDefaults]: true,
  },
  deletedEntityInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editAreaInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editArtistInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editDataInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editEventInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editGenreInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editLabelInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editMoodInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editNoteChangeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editNoteInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editNoteRecipientInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editPlaceInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editRecordingInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editReleaseInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editSeriesInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editUrlInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editWorkInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorCollectionAreaInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionArtistInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionCollaboratorInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorCollectionDeletedEntityInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionEventInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionGenreInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorCollectionInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorCollectionInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionLabelInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorCollectionTypeInMusicbrainz: {
    [structuralDefaults]: true,
    entityType: pickFrom([
      'area',
      'artist',
      'event',
      'genre',
      'instrument',
      'label',
      'place',
      'recording',
      'release',
      'release_group',
      'series',
      'work',
    ]),
  },
  editorCollectionWorkInMusicbrainz: {
    [structuralDefaults]: true,
    position: atLeast(0),
  },
  editorInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorLanguageInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorOauthTokenInMusicbrainz: {
    [structuralDefaults]: true,
    codeChallenge: null,
    codeChallengeMethod: null,
    accessToken: uniqueText('accessToken'),
    refreshToken: uniqueText('refreshToken'),
  },
  editorPreferenceInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeArtistDeletedInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeArtistInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeCollectionInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeEditorInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeLabelDeletedInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeLabelInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeSeriesDeletedInMusicbrainz: {
    [structuralDefaults]: true,
  },
  editorSubscribeSeriesInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  eventAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    eventAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    eventAttributeTypeAllowedValue: null,
  },
  eventAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    ended: false,
  },
  eventMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  eventRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  eventTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  eventTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  genderInMusicbrainz: {
    [structuralDefaults]: true,
  },
  genreAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  genreAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  genreAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  genreInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
  },
  instrumentAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  instrumentAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    instrumentAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    instrumentAttributeTypeAllowedValue: null,
  },
  instrumentAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
  },
  instrumentTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  instrumentTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  iso31661InMusicbrainz: {
    [structuralDefaults]: true,
    code: sequence((i) => base26(i, 2)),
  },
  iso31662InMusicbrainz: {
    [structuralDefaults]: true,
    code: sequence((i) => base26(i, 10)),
  },
  iso31663InMusicbrainz: {
    [structuralDefaults]: true,
    code: sequence((i) => base26(i, 4)),
  },
  isrcInMusicbrainz: {
    [structuralDefaults]: true,
    isrc: sequence((i) => `USAAA${String(i + 1).padStart(7, '0')}`),
    editsPending: atLeast(0),
  },
  iswcInMusicbrainz: {
    [structuralDefaults]: true,
    iswc: sequence((i) => iswcCode(i)),
  },
  lAreaAreaInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lAreaArtistInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaEventInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaGenreInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lAreaWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistArtistInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lArtistEventInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistGenreInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lArtistWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventEventInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lEventGenreInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lEventWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreGenreInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lGenreInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenrePlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lGenreWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentInstrumentInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lInstrumentLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lInstrumentWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelLabelInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lLabelMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lLabelWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodMoodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lMoodPlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lMoodWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlacePlaceInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lPlaceRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlaceReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlaceReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlaceSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlaceUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lPlaceWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lRecordingRecordingInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lRecordingReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lRecordingReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lRecordingSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lRecordingUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lRecordingWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseGroupReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lReleaseGroupSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseGroupUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseGroupWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseReleaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseReleaseInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lReleaseSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lReleaseWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lSeriesSeriesInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lSeriesUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lSeriesWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lUrlUrlInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  lUrlWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
  },
  lWorkWorkInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
    linkOrder: atLeast(0),
    entity0Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity1Credit: randomWords({ minLength: 3, maxLength: 30 }),
    entity0: atLeast(1),
    entity1: atLeast(2),
  },
  labelAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  labelAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    labelAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    labelAttributeTypeAllowedValue: null,
  },
  labelAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    labelCode: randomInteger(1, 999999),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    ended: false,
  },
  labelIpiInMusicbrainz: {
    [structuralDefaults]: true,
    ipi: sequence((i) => String(10000000000 + i)),
    editsPending: atLeast(0),
  },
  labelIsniInMusicbrainz: {
    [structuralDefaults]: true,
    isni: sequence((i) => String(1000000000000000 + i)),
    editsPending: atLeast(0),
  },
  labelMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  labelRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  labelTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  labelTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  languageInMusicbrainz: {
    [structuralDefaults]: true,
    isoCode2T: null,
    isoCode2B: null,
    isoCode1: null,
    isoCode3: sequence((i) => base26(i, 3)),
  },
  linkAttributeCreditInMusicbrainz: {
    [structuralDefaults]: true,
  },
  linkAttributeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  linkAttributeTextValueInMusicbrainz: {
    [structuralDefaults]: true,
    textValue: randomWords({ minLength: 3, maxLength: 30 }),
  },
  linkAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
    root: atLeast(1),
  },
  linkCreditableAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  linkInMusicbrainz: {
    [structuralDefaults]: true,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    ended: false,
  },
  linkTextAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  linkTypeAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  linkTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    mediumAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    mediumAttributeTypeAllowedValue: null,
  },
  mediumAttributeTypeAllowedFormatInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumAttributeTypeAllowedValueAllowedFormatInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumCdtocInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
  },
  mediumFormatInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  mediumInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  mediumIndexInMusicbrainz: {
    [structuralDefaults]: true,
    toc: '(1, 2, 3, 4, 5, 6)',
  },
  moodAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  moodAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  moodAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  moodInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
  },
  orderableLinkTypeInMusicbrainz: {
    [structuralDefaults]: true,
    direction: pickFrom([1, 2]),
  },
  placeAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  placeAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    placeAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    placeAttributeTypeAllowedValue: null,
  },
  placeAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    ended: false,
  },
  placeMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  placeRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  placeTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  placeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  recordingAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    recordingAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    recordingAttributeTypeAllowedValue: null,
  },
  recordingAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingFirstReleaseDateInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    length: randomInteger(1, 100000),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  recordingMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  recordingRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  recordingTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  recordingTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  releaseAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    releaseAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    releaseAttributeTypeAllowedValue: null,
  },
  releaseAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseCountryInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseFirstReleaseDateInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  releaseGroupAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    releaseGroupAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    releaseGroupAttributeTypeAllowedValue: null,
  },
  releaseGroupAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  releaseGroupMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  releaseGroupPrimaryTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  releaseGroupSecondaryTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupSecondaryTypeJoinInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseGroupTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  releaseLabelInMusicbrainz: {
    [structuralDefaults]: true,
    catalogNumber: randomWords({ minLength: 3, maxLength: 30 }),
  },
  releaseMetaInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releasePackagingInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseStatusInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  releaseUnknownCountryInMusicbrainz: {
    [structuralDefaults]: true,
    dateYear: randomInteger(1950, 2020),
    dateMonth: null,
    dateDay: null,
  },
  replicationControlInMusicbrainz: {
    [structuralDefaults]: true,
  },
  scriptInMusicbrainz: {
    [structuralDefaults]: true,
    isoCode: sequence((i) => base26(i, 4)),
  },
  seriesAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  seriesAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    seriesAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    seriesAttributeTypeAllowedValue: null,
  },
  seriesAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  seriesOrderingTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  seriesTypeInMusicbrainz: {
    [structuralDefaults]: true,
    entityType: pickFrom(['artist', 'event', 'recording', 'release', 'release_group', 'series', 'work']),
  },
  tagInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
  },
  tagRelationInMusicbrainz: {
    [structuralDefaults]: true,
    tag1: atLeast(1),
    tag2: atLeast(2),
  },
  trackGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  trackInMusicbrainz: {
    [structuralDefaults]: true,
    number: randomWords({ minLength: 3, maxLength: 30 }),
    name: randomWords({ minLength: 3, maxLength: 30 }),
    length: randomInteger(1, 100000),
    editsPending: atLeast(0),
  },
  trackRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  unreferencedRowLogInMusicbrainz: {
    [structuralDefaults]: true,
  },
  urlGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  urlInMusicbrainz: {
    [structuralDefaults]: true,
    url: sequence((i) => `https://example.com/page-${i + 1}`),
    editsPending: atLeast(0),
  },
  voteInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workAliasInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    locale: null,
    editsPending: atLeast(0),
    sortName: derive((row) => String(row.name)),
    beginDateYear: null,
    beginDateMonth: null,
    beginDateDay: null,
    endDateYear: null,
    endDateMonth: null,
    endDateDay: null,
    primaryForLocale: false,
    ended: false,
  },
  workAliasTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workAnnotationInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workAttributeInMusicbrainz: {
    [structuralDefaults]: true,
    workAttributeText: randomWords({ minLength: 3, maxLength: 30 }),
    workAttributeTypeAllowedValue: null,
  },
  workAttributeTypeAllowedValueInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workAttributeTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workGidRedirectInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workInMusicbrainz: {
    [structuralDefaults]: true,
    name: randomWords({ minLength: 3, maxLength: 30 }),
    comment: randomWords({ minLength: 3, maxLength: 30 }),
    editsPending: atLeast(0),
  },
  workLanguageInMusicbrainz: {
    [structuralDefaults]: true,
    editsPending: atLeast(0),
  },
  workMetaInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  workRatingRawInMusicbrainz: {
    [structuralDefaults]: true,
    rating: randomInteger(0, 100),
  },
  workTagInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workTagRawInMusicbrainz: {
    [structuralDefaults]: true,
  },
  workTypeInMusicbrainz: {
    [structuralDefaults]: true,
  },
} satisfies SchemaRules<typeof schema>;
