CREATE TYPE letting_status AS ENUM ('pending', 'confirmed', 'cancelled');

CREATE TABLE parks (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  region VARCHAR(40) NOT NULL,
  opened_at DATE NOT NULL,
  latitude DOUBLE PRECISION,
  amenities JSONB,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE pitches (
  id SERIAL PRIMARY KEY,
  park_id INTEGER NOT NULL REFERENCES parks (id),
  reference VARCHAR(20) NOT NULL,
  area_sqm REAL,
  has_electricity BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE owners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name VARCHAR(200) NOT NULL,
  email VARCHAR(320) NOT NULL UNIQUE,
  member_since DATE NOT NULL,
  loyalty_points BIGINT NOT NULL DEFAULT 0,
  referred_by_owner_id UUID REFERENCES owners (id)
);

CREATE TABLE holiday_homes (
  id BIGSERIAL PRIMARY KEY,
  pitch_id INTEGER NOT NULL REFERENCES pitches (id),
  owner_id UUID NOT NULL REFERENCES owners (id),
  previous_owner_id UUID REFERENCES owners (id),
  model TEXT NOT NULL,
  purchase_price NUMERIC(10, 2),
  specification JSON,
  inspected_at TIMESTAMP
);

CREATE TABLE accessories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_home_id BIGINT NOT NULL REFERENCES holiday_homes (id),
  description TEXT NOT NULL,
  quantity SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE lettings (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  holiday_home_id BIGINT NOT NULL REFERENCES holiday_homes (id),
  guest_name VARCHAR(200) NOT NULL,
  status letting_status NOT NULL DEFAULT 'pending',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  arrival_time TIME NOT NULL,
  site_fee NUMERIC(8, 2) NOT NULL,
  notes TEXT,
  CONSTRAINT lettings_holiday_home_id_start_date_key UNIQUE (holiday_home_id, start_date)
);

CREATE TABLE park_owners (
  park_id INTEGER NOT NULL REFERENCES parks (id),
  owner_id UUID NOT NULL REFERENCES owners (id),
  CONSTRAINT park_owners_park_id_owner_id_pk PRIMARY KEY (park_id, owner_id)
);
