// Rules for all 68 AdventureWorks tables. The generic mapping came from the canonical model;
// every CHECK constraint, subtype chain and cross-column date is encoded explicitly.
import { faker } from '@faker-js/faker';
import {
  type SchemaRules,
  type ValueGenerator,
  constant,
  derive,
  optional,
  pickFrom,
  randomDecimalString,
  randomInteger,
  randomWords,
  structuralDefault,
} from 'drizzle-super-seed';
import type * as schema from './schema.ts';

export const SEED = 42;
export const seedFaker = (seed: number): void => {
  faker.seed(seed);
};
seedFaker(SEED);

const rowNumber = derive((_row, context) => context.rowIndex + 1);

const PERSONS = 1000;
const VENDORS = 300;
const STORES = 200;
const EMPLOYEES = 290;
const SALESPEOPLE = 17;
const firstName = (): ValueGenerator<string> => derive(() => faker.person.firstName());
const lastName = (): ValueGenerator<string> => derive(() => faker.person.lastName());
const cityName = (): ValueGenerator<string> => derive(() => faker.location.city());
const streetAddress = (): ValueGenerator<string> => derive(() => faker.location.streetAddress());
const postalCode = (): ValueGenerator<string> => derive(() => faker.location.zipCode());
const phoneNumber = (): ValueGenerator<string> => derive(() => faker.phone.number({ style: 'national' }));
const properName = (): ValueGenerator<string> => derive(() => faker.commerce.productName().slice(0, 50));
const jobTitle = (): ValueGenerator<string> => derive(() => faker.person.jobTitle().slice(0, 50));
const emailAddress = (): ValueGenerator<string> =>
  derive(() => faker.internet.email({ provider: 'example.com' }).toLowerCase());

const isoDateBetween = (from: string, to: string): ValueGenerator<string> => {
  const start = new Date(from).getTime();
  const span = new Date(to).getTime() - start;
  return derive((_row, context) =>
    new Date(start + Math.floor(context.random.next() * span)).toISOString().slice(0, 10),
  );
};

const timestampBetween = (from: string, to: string): ValueGenerator<string> => {
  const start = new Date(from).getTime();
  const span = new Date(to).getTime() - start;
  return derive((_row, context) =>
    new Date(start + Math.floor(context.random.next() * span)).toISOString().slice(0, 19).replace('T', ' '),
  );
};

const plusDays = (timestamp: string, days: number): string =>
  new Date(new Date(`${timestamp.replace(' ', 'T')}Z`).getTime() + days * 86_400_000)
    .toISOString()
    .slice(0, 19)
    .replace('T', ' ');

const CURRENCY_CODES = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'AUD',
  'CAD',
  'CHF',
  'CNY',
  'SEK',
  'NZD',
  'MXN',
  'SGD',
  'HKD',
  'NOK',
  'KRW',
  'TRY',
  'INR',
  'BRL',
  'ZAR',
  'DKK',
  'PLN',
  'THB',
  'IDR',
  'HUF',
  'CZK',
  'ILS',
  'CLP',
  'PHP',
  'AED',
  'COP',
  'SAR',
  'MYR',
  'RON',
  'ARS',
  'VND',
  'EGP',
  'PKR',
  'NGN',
  'BDT',
  'UAH',
];

export const counts: Record<string, number> = {
  businessentityInPerson: PERSONS + VENDORS + STORES,
  personInPerson: PERSONS,
  emailaddressInPerson: PERSONS,
  passwordInPerson: PERSONS,
  personphoneInPerson: PERSONS,
  businessentityaddressInPerson: PERSONS,
  businessentitycontactInPerson: 400,
  addressInPerson: 1200,
  addresstypeInPerson: 6,
  contacttypeInPerson: 20,
  countryregionInPerson: 30,
  stateprovinceInPerson: 100,
  phonenumbertypeInPerson: 3,
  departmentInHumanresources: 16,
  employeeInHumanresources: EMPLOYEES,
  employeedepartmenthistoryInHumanresources: EMPLOYEES,
  employeepayhistoryInHumanresources: EMPLOYEES,
  jobcandidateInHumanresources: 40,
  shiftInHumanresources: 3,
  billofmaterialsInProduction: 800,
  cultureInProduction: 8,
  documentInProduction: 40,
  illustrationInProduction: 30,
  locationInProduction: 14,
  productInProduction: 500,
  productcategoryInProduction: 4,
  productsubcategoryInProduction: 37,
  productmodelInProduction: 120,
  productmodelillustrationInProduction: 60,
  productmodelproductdescriptioncultureInProduction: 300,
  productdescriptionInProduction: 300,
  productdocumentInProduction: 60,
  productinventoryInProduction: 700,
  productcosthistoryInProduction: 600,
  productlistpricehistoryInProduction: 600,
  productphotoInProduction: 100,
  productproductphotoInProduction: 500,
  productreviewInProduction: 200,
  scrapreasonInProduction: 16,
  transactionhistoryInProduction: 3000,
  transactionhistoryarchiveInProduction: 1000,
  unitmeasureInProduction: 38,
  workorderInProduction: 1500,
  workorderroutingInProduction: 2000,
  productvendorInPurchasing: 460,
  purchaseorderdetailInPurchasing: 1200,
  purchaseorderheaderInPurchasing: 400,
  shipmethodInPurchasing: 5,
  vendorInPurchasing: VENDORS,
  countryregioncurrencyInSales: 40,
  creditcardInSales: 800,
  currencyInSales: 40,
  currencyrateInSales: 400,
  customerInSales: 800,
  personcreditcardInSales: 800,
  salesorderheaderInSales: 3000,
  salesorderdetailInSales: 9000,
  salesorderheadersalesreasonInSales: 2000,
  salespersonInSales: SALESPEOPLE,
  salespersonquotahistoryInSales: 60,
  salesreasonInSales: 10,
  salestaxrateInSales: 30,
  salesterritoryInSales: 10,
  salesterritoryhistoryInSales: SALESPEOPLE,
  shoppingcartitemInSales: 100,
  specialofferInSales: 16,
  specialofferproductInSales: 500,
  storeInSales: STORES,
};

export const rules = {
  addressInPerson: {
    addressid: structuralDefault,
    addressline1: streetAddress(),
    addressline2: constant(null),
    city: cityName(),
    stateprovinceid: structuralDefault,
    postalcode: postalCode(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  addresstypeInPerson: {
    addresstypeid: structuralDefault,
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  billofmaterialsInProduction: {
    billofmaterialsid: structuralDefault,
    productassemblyid: constant(null),
    componentid: structuralDefault,
    startdate: structuralDefault,
    enddate: constant(null),
    unitmeasurecode: structuralDefault,
    bomlevel: constant(0),
    perassemblyqty: constant('1.00'),
    modifieddate: structuralDefault,
  },
  businessentityInPerson: {
    businessentityid: rowNumber,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  businessentityaddressInPerson: {
    businessentityid: rowNumber,
    addressid: structuralDefault,
    addresstypeid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  businessentitycontactInPerson: {
    businessentityid: structuralDefault,
    personid: structuralDefault,
    contacttypeid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  contacttypeInPerson: {
    contacttypeid: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  countryregionInPerson: {
    countryregioncode: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  countryregioncurrencyInSales: {
    countryregioncode: structuralDefault,
    currencycode: structuralDefault,
    modifieddate: structuralDefault,
  },
  creditcardInSales: {
    creditcardid: structuralDefault,
    cardtype: structuralDefault,
    cardnumber: structuralDefault,
    expmonth: structuralDefault,
    expyear: structuralDefault,
    modifieddate: structuralDefault,
  },
  cultureInProduction: {
    cultureid: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  currencyInSales: {
    currencycode: derive((_row, context) => CURRENCY_CODES[context.rowIndex]),
    name: properName(),
    modifieddate: structuralDefault,
  },
  currencyrateInSales: {
    currencyrateid: structuralDefault,
    currencyratedate: derive((_row, context) => plusDays('2020-01-01 00:00:00', context.rowIndex)),
    fromcurrencycode: constant('USD'),
    tocurrencycode: structuralDefault,
    averagerate: randomDecimalString(0.5, 2, 4),
    endofdayrate: randomDecimalString(0.5, 2, 4),
    modifieddate: structuralDefault,
  },
  customerInSales: {
    customerid: structuralDefault,
    personid: optional(randomInteger(1, 1000)),
    storeid: optional(randomInteger(1301, 1500)),
    territoryid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  departmentInHumanresources: {
    departmentid: structuralDefault,
    name: properName(),
    groupname: structuralDefault,
    modifieddate: structuralDefault,
  },
  documentInProduction: {
    title: properName(),
    owner: randomInteger(1, 290),
    folderflag: structuralDefault,
    filename: structuralDefault,
    fileextension: structuralDefault,
    revision: structuralDefault,
    changenumber: structuralDefault,
    status: randomInteger(1, 3),
    documentsummary: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
    documentnode: derive((_row, context) => `/doc${context.rowIndex}/`),
  },
  emailaddressInPerson: {
    businessentityid: rowNumber,
    emailaddressid: structuralDefault,
    emailaddress: emailAddress(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  employeeInHumanresources: {
    businessentityid: rowNumber,
    nationalidnumber: derive((_row, context) => String(100000000 + context.rowIndex)),
    loginid: derive((_row, context) => `adventure-works\\employee${context.rowIndex}`),
    jobtitle: jobTitle(),
    birthdate: isoDateBetween('1960-01-01', '2004-12-31'),
    maritalstatus: pickFrom(['M', 'S']),
    gender: pickFrom(['M', 'F']),
    hiredate: isoDateBetween('1996-07-01', '2025-12-31'),
    salariedflag: structuralDefault,
    vacationhours: randomInteger(-40, 240),
    sickleavehours: randomInteger(0, 120),
    currentflag: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
    organizationnode: structuralDefault,
  },
  employeedepartmenthistoryInHumanresources: {
    businessentityid: rowNumber,
    departmentid: structuralDefault,
    shiftid: structuralDefault,
    startdate: isoDateBetween('2010-01-01', '2024-12-31'),
    enddate: constant(null),
    modifieddate: structuralDefault,
  },
  employeepayhistoryInHumanresources: {
    businessentityid: rowNumber,
    ratechangedate: timestampBetween('2010-01-01', '2024-12-31'),
    rate: randomDecimalString(6.5, 200, 2),
    payfrequency: pickFrom([1, 2]),
    modifieddate: structuralDefault,
  },
  illustrationInProduction: {
    illustrationid: structuralDefault,
    modifieddate: structuralDefault,
  },
  jobcandidateInHumanresources: {
    jobcandidateid: structuralDefault,
    businessentityid: constant(null),
    modifieddate: structuralDefault,
  },
  locationInProduction: {
    locationid: structuralDefault,
    name: properName(),
    costrate: randomDecimalString(0, 60, 2),
    availability: randomDecimalString(0, 96, 2),
    modifieddate: structuralDefault,
  },
  passwordInPerson: {
    businessentityid: rowNumber,
    passwordhash: structuralDefault,
    passwordsalt: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personInPerson: {
    businessentityid: rowNumber,
    persontype: pickFrom(['SC', 'VC', 'IN', 'EM', 'SP', 'GC']),
    namestyle: constant(false),
    title: optional(pickFrom(['Mr.', 'Ms.', 'Mrs.'])),
    firstname: firstName(),
    middlename: optional(firstName()),
    lastname: lastName(),
    suffix: constant(null),
    emailpromotion: randomInteger(0, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personcreditcardInSales: {
    businessentityid: rowNumber,
    creditcardid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personphoneInPerson: {
    businessentityid: rowNumber,
    phonenumber: phoneNumber(),
    phonenumbertypeid: structuralDefault,
    modifieddate: structuralDefault,
  },
  phonenumbertypeInPerson: {
    phonenumbertypeid: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  productInProduction: {
    productid: structuralDefault,
    name: properName(),
    productnumber: structuralDefault,
    makeflag: structuralDefault,
    finishedgoodsflag: structuralDefault,
    color: structuralDefault,
    safetystocklevel: randomInteger(1, 1000),
    reorderpoint: randomInteger(1, 600),
    standardcost: randomDecimalString(1, 1500, 2),
    listprice: randomDecimalString(1, 3500, 2),
    size: structuralDefault,
    sizeunitmeasurecode: structuralDefault,
    weightunitmeasurecode: structuralDefault,
    weight: optional(randomDecimalString(1, 1000, 2)),
    daystomanufacture: randomInteger(0, 4),
    productline: optional(pickFrom(['S', 'T', 'M', 'R'])),
    class: optional(pickFrom(['L', 'M', 'H'])),
    style: optional(pickFrom(['W', 'M', 'U'])),
    productsubcategoryid: structuralDefault,
    productmodelid: structuralDefault,
    sellstartdate: timestampBetween('2011-01-01', '2020-12-31'),
    sellenddate: constant(null),
    discontinueddate: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productcategoryInProduction: {
    productcategoryid: structuralDefault,
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productcosthistoryInProduction: {
    productid: structuralDefault,
    startdate: timestampBetween('2011-01-01', '2023-12-31'),
    enddate: constant(null),
    standardcost: randomDecimalString(1, 1500, 2),
    modifieddate: structuralDefault,
  },
  productdescriptionInProduction: {
    productdescriptionid: structuralDefault,
    description: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productdocumentInProduction: {
    productid: structuralDefault,
    modifieddate: structuralDefault,
    documentnode: derive((_row, context) => `/doc${context.rowIndex % 40}/`),
  },
  productinventoryInProduction: {
    productid: structuralDefault,
    locationid: structuralDefault,
    shelf: pickFrom(['A', 'B', 'C', 'D', 'E']),
    bin: randomInteger(0, 100),
    quantity: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productlistpricehistoryInProduction: {
    productid: structuralDefault,
    startdate: timestampBetween('2011-01-01', '2023-12-31'),
    enddate: constant(null),
    listprice: randomDecimalString(1, 3500, 2),
    modifieddate: structuralDefault,
  },
  productmodelInProduction: {
    productmodelid: structuralDefault,
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productmodelillustrationInProduction: {
    productmodelid: structuralDefault,
    illustrationid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productmodelproductdescriptioncultureInProduction: {
    productmodelid: structuralDefault,
    productdescriptionid: structuralDefault,
    cultureid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productphotoInProduction: {
    productphotoid: structuralDefault,
    thumbnailphotofilename: structuralDefault,
    largephotofilename: structuralDefault,
    modifieddate: structuralDefault,
  },
  productproductphotoInProduction: {
    productid: structuralDefault,
    productphotoid: structuralDefault,
    primary: structuralDefault,
    modifieddate: structuralDefault,
  },
  productreviewInProduction: {
    productreviewid: structuralDefault,
    productid: structuralDefault,
    reviewername: structuralDefault,
    reviewdate: structuralDefault,
    emailaddress: emailAddress(),
    rating: randomInteger(1, 5),
    comments: structuralDefault,
    modifieddate: structuralDefault,
  },
  productsubcategoryInProduction: {
    productsubcategoryid: structuralDefault,
    productcategoryid: structuralDefault,
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productvendorInPurchasing: {
    productid: structuralDefault,
    businessentityid: randomInteger(1001, 1300),
    averageleadtime: randomInteger(1, 60),
    standardprice: randomDecimalString(1, 200, 2),
    lastreceiptcost: optional(randomDecimalString(1, 200, 2)),
    lastreceiptdate: structuralDefault,
    minorderqty: randomInteger(1, 10),
    maxorderqty: randomInteger(10, 1000),
    onorderqty: optional(randomInteger(0, 500)),
    unitmeasurecode: structuralDefault,
    modifieddate: structuralDefault,
  },
  purchaseorderdetailInPurchasing: {
    purchaseorderid: structuralDefault,
    purchaseorderdetailid: structuralDefault,
    duedate: timestampBetween('2012-01-01', '2025-12-31'),
    orderqty: randomInteger(1, 500),
    productid: structuralDefault,
    unitprice: randomDecimalString(0, 200, 2),
    receivedqty: randomDecimalString(0, 500, 2),
    rejectedqty: randomDecimalString(0, 10, 2),
    modifieddate: structuralDefault,
  },
  purchaseorderheaderInPurchasing: {
    purchaseorderid: structuralDefault,
    revisionnumber: structuralDefault,
    status: randomInteger(1, 4),
    employeeid: structuralDefault,
    vendorid: structuralDefault,
    shipmethodid: structuralDefault,
    orderdate: timestampBetween('2012-01-01', '2024-12-31'),
    shipdate: derive((row) => plusDays(String(row.orderdate), 10)),
    subtotal: randomDecimalString(0, 20000, 2),
    taxamt: randomDecimalString(0, 1600, 2),
    freight: randomDecimalString(0, 500, 2),
    modifieddate: structuralDefault,
  },
  salesorderdetailInSales: {
    salesorderid: structuralDefault,
    salesorderdetailid: structuralDefault,
    carriertrackingnumber: structuralDefault,
    orderqty: randomInteger(1, 12),
    productid: randomInteger(1, 500),
    specialofferid: constant(1),
    unitprice: randomDecimalString(1, 3500, 2),
    unitpricediscount: constant('0.00'),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesorderheaderInSales: {
    salesorderid: structuralDefault,
    revisionnumber: structuralDefault,
    orderdate: timestampBetween('2012-01-01', '2024-12-31'),
    duedate: derive((row) => plusDays(String(row.orderdate), 12)),
    shipdate: derive((row) => plusDays(String(row.orderdate), 7)),
    status: randomInteger(0, 8),
    onlineorderflag: structuralDefault,
    purchaseordernumber: structuralDefault,
    accountnumber: structuralDefault,
    customerid: structuralDefault,
    salespersonid: structuralDefault,
    territoryid: structuralDefault,
    billtoaddressid: structuralDefault,
    shiptoaddressid: structuralDefault,
    shipmethodid: structuralDefault,
    creditcardid: structuralDefault,
    creditcardapprovalcode: optional(randomWords({ minLength: 10, maxLength: 15 })),
    currencyrateid: structuralDefault,
    subtotal: randomDecimalString(0, 20000, 2),
    taxamt: randomDecimalString(0, 1600, 2),
    freight: randomDecimalString(0, 500, 2),
    totaldue: structuralDefault,
    comment: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesorderheadersalesreasonInSales: {
    salesorderid: structuralDefault,
    salesreasonid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salespersonInSales: {
    businessentityid: rowNumber,
    territoryid: structuralDefault,
    salesquota: optional(randomDecimalString(100000, 300000, 2)),
    bonus: randomDecimalString(0, 6000, 2),
    commissionpct: randomDecimalString(0, 0.02, 4),
    salesytd: randomDecimalString(0, 4000000, 2),
    saleslastyear: randomDecimalString(0, 4000000, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salespersonquotahistoryInSales: {
    businessentityid: randomInteger(1, 17),
    quotadate: timestampBetween('2012-01-01', '2024-12-31'),
    salesquota: randomDecimalString(100000, 300000, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesreasonInSales: {
    salesreasonid: structuralDefault,
    name: properName(),
    reasontype: structuralDefault,
    modifieddate: structuralDefault,
  },
  salestaxrateInSales: {
    salestaxrateid: structuralDefault,
    stateprovinceid: structuralDefault,
    taxtype: randomInteger(1, 3),
    taxrate: randomDecimalString(0, 20, 2),
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesterritoryInSales: {
    territoryid: structuralDefault,
    name: properName(),
    countryregioncode: structuralDefault,
    group: structuralDefault,
    salesytd: randomDecimalString(0, 8000000, 2),
    saleslastyear: randomDecimalString(0, 8000000, 2),
    costytd: constant('0.00'),
    costlastyear: constant('0.00'),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesterritoryhistoryInSales: {
    businessentityid: rowNumber,
    territoryid: structuralDefault,
    startdate: timestampBetween('2012-01-01', '2020-12-31'),
    enddate: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  scrapreasonInProduction: {
    scrapreasonid: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  shiftInHumanresources: {
    shiftid: structuralDefault,
    name: properName(),
    starttime: structuralDefault,
    endtime: structuralDefault,
    modifieddate: structuralDefault,
  },
  shipmethodInPurchasing: {
    shipmethodid: structuralDefault,
    name: properName(),
    shipbase: randomDecimalString(1, 30, 2),
    shiprate: randomDecimalString(1, 5, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  shoppingcartitemInSales: {
    shoppingcartitemid: structuralDefault,
    shoppingcartid: structuralDefault,
    quantity: randomInteger(1, 6),
    productid: structuralDefault,
    datecreated: structuralDefault,
    modifieddate: structuralDefault,
  },
  specialofferInSales: {
    specialofferid: structuralDefault,
    description: structuralDefault,
    discountpct: randomDecimalString(0, 0.4, 2),
    type: structuralDefault,
    category: structuralDefault,
    startdate: timestampBetween('2012-01-01', '2020-12-31'),
    enddate: derive((row) => plusDays(String(row.startdate), 365)),
    minqty: randomInteger(0, 4),
    maxqty: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  specialofferproductInSales: {
    specialofferid: constant(1),
    productid: rowNumber,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  stateprovinceInPerson: {
    stateprovinceid: structuralDefault,
    stateprovincecode: structuralDefault,
    countryregioncode: structuralDefault,
    isonlystateprovinceflag: structuralDefault,
    name: properName(),
    territoryid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  storeInSales: {
    businessentityid: derive((_row, context) => 1300 + context.rowIndex + 1),
    name: properName(),
    salespersonid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  transactionhistoryInProduction: {
    transactionid: structuralDefault,
    productid: structuralDefault,
    referenceorderid: structuralDefault,
    referenceorderlineid: structuralDefault,
    transactiondate: structuralDefault,
    transactiontype: pickFrom(['W', 'S', 'P']),
    quantity: structuralDefault,
    actualcost: structuralDefault,
    modifieddate: structuralDefault,
  },
  transactionhistoryarchiveInProduction: {
    transactionid: structuralDefault,
    productid: structuralDefault,
    referenceorderid: structuralDefault,
    referenceorderlineid: structuralDefault,
    transactiondate: structuralDefault,
    transactiontype: pickFrom(['W', 'S', 'P']),
    quantity: structuralDefault,
    actualcost: structuralDefault,
    modifieddate: structuralDefault,
  },
  unitmeasureInProduction: {
    unitmeasurecode: structuralDefault,
    name: properName(),
    modifieddate: structuralDefault,
  },
  vendorInPurchasing: {
    businessentityid: derive((_row, context) => 1000 + context.rowIndex + 1),
    accountnumber: derive((_row, context) => `VENDOR${String(context.rowIndex).padStart(7, '0')}`),
    name: properName(),
    creditrating: randomInteger(1, 5),
    preferredvendorstatus: structuralDefault,
    activeflag: structuralDefault,
    purchasingwebserviceurl: structuralDefault,
    modifieddate: structuralDefault,
  },
  workorderInProduction: {
    workorderid: structuralDefault,
    productid: structuralDefault,
    orderqty: randomInteger(1, 60),
    scrappedqty: randomInteger(0, 5),
    startdate: timestampBetween('2012-01-01', '2024-12-31'),
    enddate: constant(null),
    duedate: structuralDefault,
    scrapreasonid: structuralDefault,
    modifieddate: structuralDefault,
  },
  workorderroutingInProduction: {
    workorderid: structuralDefault,
    productid: structuralDefault,
    operationsequence: structuralDefault,
    locationid: structuralDefault,
    scheduledstartdate: timestampBetween('2012-01-01', '2024-12-31'),
    scheduledenddate: derive((row) => plusDays(String(row.scheduledstartdate), 14)),
    actualstartdate: constant(null),
    actualenddate: constant(null),
    actualresourcehrs: constant(null),
    plannedcost: randomDecimalString(1, 200, 2),
    actualcost: constant(null),
    modifieddate: structuralDefault,
  },
} satisfies SchemaRules<typeof schema>;
