// Rules for all 68 AdventureWorks tables. The generic mapping came from the canonical model;
// every CHECK constraint, subtype chain and cross-column date is encoded explicitly.
import { faker } from '@faker-js/faker';
import {
  type SchemaRules,
  type ValueGenerator,
  constant,
  derive,
  optional,
  pickFrom,
  randomDecimalString,
  randomInteger,
  randomWords,
  structuralDefault,
} from 'drizzle-super-seed';
import type * as schema from './schema.ts';

export const SEED = 42;
export const seedFaker = (seed: number): void => {
  faker.seed(seed);
};
seedFaker(SEED);

const rowNumber = derive((_row, context) => context.rowIndex + 1);

const PRODUCT_COUNT = 500;

const PERSONS = 1000;
const VENDORS = 300;
const STORES = 200;
const EMPLOYEES = 290;
const SALESPEOPLE = 17;
const firstName = (): ValueGenerator<string> => derive(() => faker.person.firstName());
const lastName = (): ValueGenerator<string> => derive(() => faker.person.lastName());
const cityName = (): ValueGenerator<string> => derive(() => faker.location.city());
const streetAddress = (): ValueGenerator<string> => derive(() => faker.location.streetAddress());
const postalCode = (): ValueGenerator<string> => derive(() => faker.location.zipCode());
const phoneNumber = (): ValueGenerator<string> => derive(() => faker.phone.number({ style: 'national' }));
const properName = (): ValueGenerator<string> => derive(() => faker.commerce.productName().slice(0, 50));
const jobTitle = (): ValueGenerator<string> => derive(() => faker.person.jobTitle().slice(0, 50));
const emailAddress = (): ValueGenerator<string> =>
  derive(() => faker.internet.email({ provider: 'example.com' }).toLowerCase());

const isoDateBetween = (from: string, to: string): ValueGenerator<string> => {
  const start = new Date(from).getTime();
  const span = new Date(to).getTime() - start;
  return derive((_row, context) =>
    new Date(start + Math.floor(context.random.next() * span)).toISOString().slice(0, 10),
  );
};

const timestampBetween = (from: string, to: string): ValueGenerator<string> => {
  const start = new Date(from).getTime();
  const span = new Date(to).getTime() - start;
  return derive((_row, context) =>
    new Date(start + Math.floor(context.random.next() * span)).toISOString().slice(0, 19).replace('T', ' '),
  );
};

const plusDays = (timestamp: string, days: number): string =>
  new Date(new Date(`${timestamp.replace(' ', 'T')}Z`).getTime() + days * 86_400_000)
    .toISOString()
    .slice(0, 19)
    .replace('T', ' ');

const CURRENCY_CODES = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'AUD',
  'CAD',
  'CHF',
  'CNY',
  'SEK',
  'NZD',
  'MXN',
  'SGD',
  'HKD',
  'NOK',
  'KRW',
  'TRY',
  'INR',
  'BRL',
  'ZAR',
  'DKK',
  'PLN',
  'THB',
  'IDR',
  'HUF',
  'CZK',
  'ILS',
  'CLP',
  'PHP',
  'AED',
  'COP',
  'SAR',
  'MYR',
  'RON',
  'ARS',
  'VND',
  'EGP',
  'PKR',
  'NGN',
  'BDT',
  'UAH',
];

// AdventureWorks is a bicycle manufacturer, and its reference tables have fixed real contents.
// Each list below is that content; the rules index it by row number, so values are realistic,
// deterministic and unique where the column is a key. Counts match the list lengths.
const COUNTRY_REGIONS: Array<[string, string]> = [
  ['US', 'United States'],
  ['CA', 'Canada'],
  ['GB', 'United Kingdom'],
  ['FR', 'France'],
  ['DE', 'Germany'],
  ['AU', 'Australia'],
  ['IT', 'Italy'],
  ['ES', 'Spain'],
  ['JP', 'Japan'],
  ['CN', 'China'],
  ['IN', 'India'],
  ['BR', 'Brazil'],
  ['MX', 'Mexico'],
  ['NL', 'Netherlands'],
  ['BE', 'Belgium'],
  ['SE', 'Sweden'],
  ['NO', 'Norway'],
  ['DK', 'Denmark'],
  ['FI', 'Finland'],
  ['IE', 'Ireland'],
  ['PT', 'Portugal'],
  ['AT', 'Austria'],
  ['CH', 'Switzerland'],
  ['PL', 'Poland'],
  ['CZ', 'Czechia'],
  ['GR', 'Greece'],
  ['NZ', 'New Zealand'],
  ['ZA', 'South Africa'],
  ['KR', 'South Korea'],
  ['SG', 'Singapore'],
];

const STATE_PROVINCES: Array<[string, string, string]> = [
  ['AL', 'Alabama', 'US'],
  ['AZ', 'Arizona', 'US'],
  ['CA', 'California', 'US'],
  ['CO', 'Colorado', 'US'],
  ['FL', 'Florida', 'US'],
  ['GA', 'Georgia', 'US'],
  ['IL', 'Illinois', 'US'],
  ['MA', 'Massachusetts', 'US'],
  ['MI', 'Michigan', 'US'],
  ['MN', 'Minnesota', 'US'],
  ['MO', 'Missouri', 'US'],
  ['NV', 'Nevada', 'US'],
  ['NJ', 'New Jersey', 'US'],
  ['NY', 'New York', 'US'],
  ['NC', 'North Carolina', 'US'],
  ['OH', 'Ohio', 'US'],
  ['OR', 'Oregon', 'US'],
  ['PA', 'Pennsylvania', 'US'],
  ['TX', 'Texas', 'US'],
  ['UT', 'Utah', 'US'],
  ['VA', 'Virginia', 'US'],
  ['WA', 'Washington', 'US'],
  ['WI', 'Wisconsin', 'US'],
  ['AB', 'Alberta', 'CA'],
  ['BC', 'British Columbia', 'CA'],
  ['MB', 'Manitoba', 'CA'],
  ['ON', 'Ontario', 'CA'],
  ['QC', 'Quebec', 'CA'],
  ['SK', 'Saskatchewan', 'CA'],
  ['ENG', 'England', 'GB'],
  ['SCT', 'Scotland', 'GB'],
  ['WLS', 'Wales', 'GB'],
  ['IDF', 'Ile-de-France', 'FR'],
  ['NAQ', 'Nouvelle-Aquitaine', 'FR'],
  ['OCC', 'Occitanie', 'FR'],
  ['BY', 'Bayern', 'DE'],
  ['BW', 'Baden-Wurttemberg', 'DE'],
  ['NW', 'Nordrhein-Westfalen', 'DE'],
  ['NSW', 'New South Wales', 'AU'],
  ['QLD', 'Queensland', 'AU'],
  ['VIC', 'Victoria', 'AU'],
  ['TAS', 'Tasmania', 'AU'],
];

const CULTURES: Array<[string, string]> = [
  ['en', 'English'],
  ['ar', 'Arabic'],
  ['fr', 'French'],
  ['th', 'Thai'],
  ['he', 'Hebrew'],
  ['zh-cht', 'Chinese'],
  ['es', 'Spanish'],
  ['de', 'German'],
];

const CURRENCIES: Array<[string, string]> = [
  ['USD', 'US Dollar'],
  ['EUR', 'Euro'],
  ['GBP', 'Pound Sterling'],
  ['JPY', 'Japanese Yen'],
  ['AUD', 'Australian Dollar'],
  ['CAD', 'Canadian Dollar'],
  ['CHF', 'Swiss Franc'],
  ['CNY', 'Renminbi'],
  ['SEK', 'Swedish Krona'],
  ['NZD', 'New Zealand Dollar'],
  ['MXN', 'Mexican Peso'],
  ['SGD', 'Singapore Dollar'],
  ['HKD', 'Hong Kong Dollar'],
  ['NOK', 'Norwegian Krone'],
  ['KRW', 'South Korean Won'],
  ['TRY', 'Turkish Lira'],
  ['INR', 'Indian Rupee'],
  ['BRL', 'Brazilian Real'],
  ['ZAR', 'South African Rand'],
  ['DKK', 'Danish Krone'],
];

const UNIT_MEASURES: Array<[string, string]> = [
  ['CM', 'Centimeter'],
  ['M', 'Meter'],
  ['MM', 'Millimeter'],
  ['IN', 'Inch'],
  ['FT', 'Foot'],
  ['G', 'Gram'],
  ['KG', 'Kilogram'],
  ['LB', 'Pound'],
  ['OZ', 'Ounce'],
  ['EA', 'Each'],
  ['PC', 'Piece'],
  ['PAK', 'Pack'],
  ['BOX', 'Boxes'],
  ['CS', 'Case'],
  ['CTN', 'Carton'],
  ['DZ', 'Dozen'],
  ['PAL', 'Pallet'],
  ['SET', 'Set'],
  ['ROL', 'Roll'],
  ['BTL', 'Bottle'],
];

const DEPARTMENTS: Array<[string, string]> = [
  ['Engineering', 'Research and Development'],
  ['Tool Design', 'Research and Development'],
  ['Sales', 'Sales and Marketing'],
  ['Marketing', 'Sales and Marketing'],
  ['Purchasing', 'Inventory Management'],
  ['Research and Development', 'Research and Development'],
  ['Production', 'Manufacturing'],
  ['Production Control', 'Manufacturing'],
  ['Human Resources', 'Executive General and Administration'],
  ['Finance', 'Executive General and Administration'],
  ['Information Services', 'Executive General and Administration'],
  ['Document Control', 'Quality Assurance'],
  ['Quality Assurance', 'Quality Assurance'],
  ['Facilities and Maintenance', 'Executive General and Administration'],
  ['Shipping and Receiving', 'Inventory Management'],
  ['Executive', 'Executive General and Administration'],
];

const SHIFTS: Array<[string, string, string]> = [
  ['Day', '07:00:00', '15:00:00'],
  ['Evening', '15:00:00', '23:00:00'],
  ['Night', '23:00:00', '07:00:00'],
];

const ADDRESS_TYPES = ['Billing', 'Home', 'Main Office', 'Primary', 'Shipping', 'Archive'];

const CONTACT_TYPES = [
  'Accounting Manager',
  'Assistant Sales Agent',
  'Assistant Sales Representative',
  'Coordinator Foreign Markets',
  'Export Administrator',
  'International Marketing Manager',
  'Marketing Assistant',
  'Marketing Manager',
  'Marketing Representative',
  'Order Administrator',
  'Owner',
  'Owner/Marketing Assistant',
  'Product Manager',
  'Purchasing Agent',
  'Purchasing Manager',
  'Regional Account Representative',
  'Sales Agent',
  'Sales Associate',
  'Sales Manager',
  'Sales Representative',
];

const PHONE_NUMBER_TYPES = ['Cell', 'Home', 'Work'];

const PRODUCT_CATEGORIES = ['Bikes', 'Components', 'Clothing', 'Accessories'];

// Each subcategory names the category it belongs under, by its position in PRODUCT_CATEGORIES.
const PRODUCT_SUBCATEGORIES: Array<[string, number]> = [
  ['Mountain Bikes', 0],
  ['Road Bikes', 0],
  ['Touring Bikes', 0],
  ['Handlebars', 1],
  ['Bottom Brackets', 1],
  ['Brakes', 1],
  ['Chains', 1],
  ['Cranksets', 1],
  ['Derailleurs', 1],
  ['Forks', 1],
  ['Headsets', 1],
  ['Mountain Frames', 1],
  ['Pedals', 1],
  ['Road Frames', 1],
  ['Saddles', 1],
  ['Touring Frames', 1],
  ['Wheels', 1],
  ['Bib-Shorts', 2],
  ['Caps', 2],
  ['Gloves', 2],
  ['Jerseys', 2],
  ['Shorts', 2],
  ['Socks', 2],
  ['Tights', 2],
  ['Vests', 2],
  ['Bike Racks', 3],
  ['Bike Stands', 3],
  ['Bottles and Cages', 3],
  ['Cleaners', 3],
  ['Fenders', 3],
  ['Helmets', 3],
  ['Hydration Packs', 3],
  ['Lights', 3],
  ['Locks', 3],
  ['Panniers', 3],
  ['Pumps', 3],
  ['Tires and Tubes', 3],
];

const PRODUCT_MODELS = [
  'Mountain-100',
  'Mountain-200',
  'Mountain-300',
  'Mountain-400',
  'Mountain-500',
  'Road-150',
  'Road-250',
  'Road-350',
  'Road-450',
  'Road-550',
  'Road-650',
  'Road-750',
  'Touring-1000',
  'Touring-2000',
  'Touring-3000',
  'Sport-100',
  'HL Mountain Frame',
  'LL Road Frame',
  'ML Touring Frame',
  'Classic Vest',
  'Cycling Cap',
  'Full-Finger Gloves',
  'Half-Finger Gloves',
  'Long-Sleeve Logo Jersey',
  'Short-Sleeve Classic Jersey',
  'Mountain Bike Socks',
  'Racing Socks',
  "Women's Mountain Shorts",
  "Men's Bib-Shorts",
  'Hydration Pack',
  'Water Bottle',
  'Mountain Tire Tube',
  'Road Tire Tube',
  'Patch Kit',
  'Chain',
  'Front Derailleur',
  'Rear Derailleur',
  'Headlights - Dual-Beam',
  'Taillights',
  'Cable Lock',
  'Minipump',
  'Mountain Pedal',
  'Road Pedal',
  'Fender Set - Mountain',
];

const PRODUCT_COLOURS = ['Black', 'Silver', 'Red', 'Blue', 'Yellow', 'Grey', 'Multi', 'White'];

const PRODUCT_SIZES = [
  '38',
  '40',
  '42',
  '44',
  '46',
  '48',
  '50',
  '52',
  '54',
  '56',
  '58',
  '60',
  '62',
  'S',
  'M',
  'L',
  'XL',
];

const PRODUCT_NUMBER_PREFIXES = [
  'BK',
  'BC',
  'BE',
  'CA',
  'CL',
  'CS',
  'FR',
  'HB',
  'HE',
  'LO',
  'PD',
  'RA',
  'SO',
  'ST',
  'TI',
  'WB',
];

const LOCATIONS: Array<[string, string, string]> = [
  ['Tool Crib', '0.00', '0.00'],
  ['Sheet Metal Racks', '0.00', '0.00'],
  ['Paint Shop', '0.00', '0.00'],
  ['Paint Storage', '0.00', '0.00'],
  ['Metal Storage', '0.00', '0.00'],
  ['Miscellaneous Storage', '0.00', '0.00'],
  ['Finished Goods Storage', '0.00', '0.00'],
  ['Frame Forming', '22.50', '96.00'],
  ['Frame Welding', '25.00', '108.00'],
  ['Debur and Polish', '14.50', '120.00'],
  ['Paint', '15.75', '120.00'],
  ['Specialized Paint', '18.00', '80.00'],
  ['Subassembly', '12.25', '120.00'],
  ['Final Assembly', '12.25', '120.00'],
];

const SCRAP_REASONS = [
  'Brake assembly not as ordered',
  'Color incorrect',
  'Drill pattern incorrect',
  'Drill size too large',
  'Drill size too small',
  'Gouge in metal',
  'Handling damage',
  'Incorrect activity performed',
  'Paint process failed',
  'Primer process failed',
  'Seat assembly not as ordered',
  'Stress test failed',
  'Thermoform temperature too high',
  'Thermoform temperature too low',
  'Trim length too long',
  'Wheel misaligned',
];

const SHIP_METHODS: Array<[string, string, string]> = [
  ['XRQ - TRUCK GROUND', '3.95', '0.99'],
  ['ZY - EXPRESS', '9.95', '1.99'],
  ['OVERSEAS - DELUXE', '29.95', '2.99'],
  ['OVERNIGHT J-FAST', '21.95', '1.29'],
  ['CARGO TRANSPORT 5', '8.99', '1.49'],
];

const SALES_REASONS: Array<[string, string]> = [
  ['Price', 'Other'],
  ['On Promotion', 'Promotion'],
  ['Magazine Advertisement', 'Marketing'],
  ['Television Advertisement', 'Marketing'],
  ['Manufacturer', 'Other'],
  ['Review', 'Other'],
  ['Demo Event', 'Marketing'],
  ['Sponsorship', 'Marketing'],
  ['Quality', 'Other'],
  ['Other', 'Other'],
];

const SALES_TERRITORIES: Array<[string, string, string]> = [
  ['Northwest', 'US', 'North America'],
  ['Northeast', 'US', 'North America'],
  ['Central', 'US', 'North America'],
  ['Southwest', 'US', 'North America'],
  ['Southeast', 'US', 'North America'],
  ['Canada', 'CA', 'North America'],
  ['France', 'FR', 'Europe'],
  ['Germany', 'DE', 'Europe'],
  ['Australia', 'AU', 'Pacific'],
  ['United Kingdom', 'GB', 'Europe'],
];

const SPECIAL_OFFERS: Array<[string, string, string, string]> = [
  ['No Discount', 'No Discount', 'No Discount', '0.00'],
  ['Volume Discount 11 to 14', 'Volume Discount', 'Reseller', '0.02'],
  ['Volume Discount 15 to 24', 'Volume Discount', 'Reseller', '0.05'],
  ['Volume Discount 25 to 40', 'Volume Discount', 'Reseller', '0.10'],
  ['Volume Discount 41 to 60', 'Volume Discount', 'Reseller', '0.15'],
  ['Volume Discount over 60', 'Volume Discount', 'Reseller', '0.20'],
  ['Mountain-100 Clearance Sale', 'Discontinued Product', 'Reseller', '0.35'],
  ['Sport Helmet Discount-2002', 'Seasonal Discount', 'Reseller', '0.10'],
  ['Road-650 Overstock', 'Excess Inventory', 'Reseller', '0.30'],
  ['Mountain Tire Sale', 'Excess Inventory', 'Customer', '0.50'],
  ['Sport Helmet Discount-2003', 'Seasonal Discount', 'Reseller', '0.15'],
  ['LL Road Frame Sale', 'Excess Inventory', 'Reseller', '0.35'],
  ['Touring-3000 Promotion', 'New Product', 'Reseller', '0.15'],
  ['Touring-1000 Promotion', 'New Product', 'Reseller', '0.20'],
  ['Half-Price Pedal Sale', 'Seasonal Discount', 'Customer', '0.50'],
  ['Mountain Bike Kit Discount', 'Discontinued Product', 'Reseller', '0.20'],
];

const CARD_TYPES = ['SuperiorCard', 'Distinguish', 'ColonialVoice', 'Vista'];

const DOCUMENT_TITLES = [
  'Crank Arm and Tire Maintenance',
  'Front Reflector Bracket Installation',
  'Repair and Service Guidelines',
  'Lubrication Maintenance',
  'Seat Assembly',
  'Installing Replacement Pedals',
  'Training Wheels Installation',
  'Wheel Maintenance',
  'Chain Replacement Procedure',
  'Brake Adjustment Guidelines',
];

const PERSON_TITLES = ['Mr.', 'Ms.', 'Mrs.', 'Dr.', 'Sr.'];

// Row-indexed pick: deterministic, and unique per row while the list is at least as long as
// the count, which is how the reference tables above keep their keys distinct.
const fromList = <TValue>(values: readonly TValue[]): ValueGenerator<TValue> =>
  derive((_row, context) => values[context.rowIndex % values.length]);

export const counts: Record<string, number> = {
  businessentityInPerson: PERSONS + VENDORS + STORES,
  personInPerson: PERSONS,
  emailaddressInPerson: PERSONS,
  passwordInPerson: PERSONS,
  personphoneInPerson: PERSONS,
  businessentityaddressInPerson: PERSONS,
  businessentitycontactInPerson: 400,
  addressInPerson: 1200,
  addresstypeInPerson: ADDRESS_TYPES.length,
  contacttypeInPerson: CONTACT_TYPES.length,
  countryregionInPerson: COUNTRY_REGIONS.length,
  stateprovinceInPerson: STATE_PROVINCES.length,
  phonenumbertypeInPerson: PHONE_NUMBER_TYPES.length,
  departmentInHumanresources: DEPARTMENTS.length,
  employeeInHumanresources: EMPLOYEES,
  employeedepartmenthistoryInHumanresources: EMPLOYEES,
  employeepayhistoryInHumanresources: EMPLOYEES,
  jobcandidateInHumanresources: 40,
  shiftInHumanresources: SHIFTS.length,
  billofmaterialsInProduction: 800,
  cultureInProduction: CULTURES.length,
  documentInProduction: DOCUMENT_TITLES.length,
  illustrationInProduction: 30,
  locationInProduction: LOCATIONS.length,
  productInProduction: PRODUCT_COUNT,
  productcategoryInProduction: PRODUCT_CATEGORIES.length,
  productsubcategoryInProduction: PRODUCT_SUBCATEGORIES.length,
  productmodelInProduction: PRODUCT_MODELS.length,
  productmodelillustrationInProduction: 60,
  productmodelproductdescriptioncultureInProduction: 300,
  productdescriptionInProduction: 300,
  productdocumentInProduction: 60,
  productinventoryInProduction: 700,
  productcosthistoryInProduction: 600,
  productlistpricehistoryInProduction: 600,
  productphotoInProduction: 100,
  productproductphotoInProduction: 500,
  productreviewInProduction: 200,
  scrapreasonInProduction: SCRAP_REASONS.length,
  transactionhistoryInProduction: 3000,
  transactionhistoryarchiveInProduction: 1000,
  unitmeasureInProduction: UNIT_MEASURES.length,
  workorderInProduction: 1500,
  workorderroutingInProduction: 2000,
  productvendorInPurchasing: 460,
  purchaseorderdetailInPurchasing: 1200,
  purchaseorderheaderInPurchasing: 400,
  shipmethodInPurchasing: SHIP_METHODS.length,
  vendorInPurchasing: VENDORS,
  countryregioncurrencyInSales: 40,
  creditcardInSales: 800,
  currencyInSales: CURRENCIES.length,
  currencyrateInSales: 400,
  customerInSales: 800,
  personcreditcardInSales: 800,
  salesorderheaderInSales: 3000,
  salesorderdetailInSales: 9000,
  salesorderheadersalesreasonInSales: 2000,
  salespersonInSales: SALESPEOPLE,
  salespersonquotahistoryInSales: 60,
  salesreasonInSales: SALES_REASONS.length,
  salestaxrateInSales: 30,
  salesterritoryInSales: SALES_TERRITORIES.length,
  salesterritoryhistoryInSales: SALESPEOPLE,
  shoppingcartitemInSales: 100,
  specialofferInSales: SPECIAL_OFFERS.length,
  specialofferproductInSales: 500,
  storeInSales: STORES,
};

export const rules = {
  addressInPerson: {
    addressid: structuralDefault,
    addressline1: streetAddress(),
    addressline2: constant(null),
    city: cityName(),
    stateprovinceid: structuralDefault,
    postalcode: postalCode(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  addresstypeInPerson: {
    addresstypeid: structuralDefault,
    name: fromList(ADDRESS_TYPES),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  billofmaterialsInProduction: {
    billofmaterialsid: structuralDefault,
    productassemblyid: constant(null),
    // CK_BillOfMaterials_ProductAssemblyID (productassemblyid <> componentid) names only
    // foreign keys, so the structural default is refused even though the null assembly above
    // already satisfies it. A product row number keeps the reference valid explicitly.
    componentid: derive((_row, context) => (context.rowIndex % PRODUCT_COUNT) + 1),
    // CK_BillOfMaterials_EndDate relates startdate to enddate, so the structural default is
    // refused here even though a null enddate already satisfies it. Any explicit value will do.
    startdate: derive((_row, context) => context.referenceDate.toISOString()),
    enddate: constant(null),
    unitmeasurecode: structuralDefault,
    bomlevel: constant(0),
    perassemblyqty: constant('1.00'),
    modifieddate: structuralDefault,
  },
  businessentityInPerson: {
    businessentityid: rowNumber,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  businessentityaddressInPerson: {
    businessentityid: rowNumber,
    addressid: structuralDefault,
    addresstypeid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  businessentitycontactInPerson: {
    businessentityid: structuralDefault,
    personid: structuralDefault,
    contacttypeid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  contacttypeInPerson: {
    contacttypeid: structuralDefault,
    name: fromList(CONTACT_TYPES),
    modifieddate: structuralDefault,
  },
  countryregionInPerson: {
    countryregioncode: derive((_row, context) => COUNTRY_REGIONS[context.rowIndex][0]),
    name: derive((_row, context) => COUNTRY_REGIONS[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  countryregioncurrencyInSales: {
    countryregioncode: structuralDefault,
    currencycode: structuralDefault,
    modifieddate: structuralDefault,
  },
  creditcardInSales: {
    creditcardid: structuralDefault,
    cardtype: fromList(CARD_TYPES),
    cardnumber: derive((_row, context) => String(11111111111111 + context.rowIndex * 7)),
    expmonth: randomInteger(1, 12),
    expyear: randomInteger(2026, 2032),
    modifieddate: structuralDefault,
  },
  cultureInProduction: {
    cultureid: derive((_row, context) => CULTURES[context.rowIndex][0]),
    name: derive((_row, context) => CULTURES[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  currencyInSales: {
    currencycode: derive((_row, context) => CURRENCIES[context.rowIndex][0]),
    name: derive((_row, context) => CURRENCIES[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  currencyrateInSales: {
    currencyrateid: structuralDefault,
    currencyratedate: derive((_row, context) => plusDays('2020-01-01 00:00:00', context.rowIndex)),
    fromcurrencycode: constant('USD'),
    tocurrencycode: structuralDefault,
    averagerate: randomDecimalString(0.5, 2, 4),
    endofdayrate: randomDecimalString(0.5, 2, 4),
    modifieddate: structuralDefault,
  },
  customerInSales: {
    customerid: structuralDefault,
    personid: optional(randomInteger(1, 1000)),
    storeid: optional(randomInteger(1301, 1500)),
    territoryid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  departmentInHumanresources: {
    departmentid: structuralDefault,
    name: derive((_row, context) => DEPARTMENTS[context.rowIndex][0]),
    groupname: derive((_row, context) => DEPARTMENTS[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  documentInProduction: {
    title: fromList(DOCUMENT_TITLES),
    owner: randomInteger(1, EMPLOYEES),
    folderflag: structuralDefault,
    filename: derive((_row, context) => `${DOCUMENT_TITLES[context.rowIndex % DOCUMENT_TITLES.length]}.doc`),
    fileextension: constant('.doc'),
    revision: derive((_row, context) => String(context.rowIndex % 10)),
    changenumber: structuralDefault,
    status: randomInteger(1, 3),
    documentsummary: derive(() => faker.lorem.sentence()),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
    documentnode: derive((_row, context) => `/doc${context.rowIndex}/`),
  },
  emailaddressInPerson: {
    businessentityid: rowNumber,
    emailaddressid: structuralDefault,
    emailaddress: emailAddress(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  employeeInHumanresources: {
    businessentityid: rowNumber,
    nationalidnumber: derive((_row, context) => String(100000000 + context.rowIndex)),
    loginid: derive((_row, context) => `adventure-works\\employee${context.rowIndex}`),
    jobtitle: jobTitle(),
    birthdate: isoDateBetween('1960-01-01', '2004-12-31'),
    maritalstatus: pickFrom(['M', 'S']),
    gender: pickFrom(['M', 'F']),
    hiredate: isoDateBetween('1996-07-01', '2025-12-31'),
    salariedflag: structuralDefault,
    vacationhours: randomInteger(-40, 240),
    sickleavehours: randomInteger(0, 120),
    currentflag: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
    organizationnode: structuralDefault,
  },
  employeedepartmenthistoryInHumanresources: {
    businessentityid: rowNumber,
    departmentid: structuralDefault,
    shiftid: structuralDefault,
    startdate: isoDateBetween('2010-01-01', '2024-12-31'),
    enddate: constant(null),
    modifieddate: structuralDefault,
  },
  employeepayhistoryInHumanresources: {
    businessentityid: rowNumber,
    ratechangedate: timestampBetween('2010-01-01', '2024-12-31'),
    rate: randomDecimalString(6.5, 200, 2),
    payfrequency: pickFrom([1, 2]),
    modifieddate: structuralDefault,
  },
  illustrationInProduction: {
    illustrationid: structuralDefault,
    modifieddate: structuralDefault,
  },
  jobcandidateInHumanresources: {
    jobcandidateid: structuralDefault,
    businessentityid: constant(null),
    modifieddate: structuralDefault,
  },
  locationInProduction: {
    locationid: structuralDefault,
    name: derive((_row, context) => LOCATIONS[context.rowIndex][0]),
    costrate: derive((_row, context) => LOCATIONS[context.rowIndex][1]),
    availability: derive((_row, context) => LOCATIONS[context.rowIndex][2]),
    modifieddate: structuralDefault,
  },
  passwordInPerson: {
    businessentityid: rowNumber,
    passwordhash: derive(() => faker.string.alphanumeric({ length: 44 })),
    passwordsalt: derive(() => faker.string.alphanumeric({ length: 8 })),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personInPerson: {
    businessentityid: rowNumber,
    persontype: pickFrom(['SC', 'VC', 'IN', 'EM', 'SP', 'GC']),
    namestyle: constant(false),
    title: optional(pickFrom(['Mr.', 'Ms.', 'Mrs.'])),
    firstname: firstName(),
    middlename: optional(firstName()),
    lastname: lastName(),
    suffix: constant(null),
    emailpromotion: randomInteger(0, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personcreditcardInSales: {
    businessentityid: rowNumber,
    creditcardid: structuralDefault,
    modifieddate: structuralDefault,
  },
  personphoneInPerson: {
    businessentityid: rowNumber,
    phonenumber: phoneNumber(),
    phonenumbertypeid: structuralDefault,
    modifieddate: structuralDefault,
  },
  phonenumbertypeInPerson: {
    phonenumbertypeid: structuralDefault,
    name: fromList(PHONE_NUMBER_TYPES),
    modifieddate: structuralDefault,
  },
  productInProduction: {
    productid: structuralDefault,
    // AdventureWorks names a product for its model, colour and size: "Mountain-100 Black, 42".
    name: derive((_row, context) => {
      const model = PRODUCT_MODELS[context.rowIndex % PRODUCT_MODELS.length];
      const colour = PRODUCT_COLOURS[context.rowIndex % PRODUCT_COLOURS.length];
      const size = PRODUCT_SIZES[context.rowIndex % PRODUCT_SIZES.length];
      return `${model} ${colour}, ${size}`.slice(0, 50);
    }),
    productnumber: derive(
      (_row, context) =>
        `${PRODUCT_NUMBER_PREFIXES[context.rowIndex % PRODUCT_NUMBER_PREFIXES.length]}-${String(context.rowIndex + 1).padStart(5, '0')}`,
    ),
    makeflag: structuralDefault,
    finishedgoodsflag: structuralDefault,
    color: optional(fromList(PRODUCT_COLOURS)),
    safetystocklevel: randomInteger(1, 1000),
    reorderpoint: randomInteger(1, 600),
    standardcost: randomDecimalString(1, 1500, 2),
    listprice: randomDecimalString(1, 3500, 2),
    size: optional(fromList(PRODUCT_SIZES)),
    // Sizes are centimetres and weights grams, as the bicycle catalogue records them, rather
    // than whichever unit the pool happens to offer.
    sizeunitmeasurecode: constant('CM'),
    weightunitmeasurecode: constant('G'),
    weight: optional(randomDecimalString(1, 1000, 2)),
    daystomanufacture: randomInteger(0, 4),
    productline: optional(pickFrom(['S', 'T', 'M', 'R'])),
    class: optional(pickFrom(['L', 'M', 'H'])),
    style: optional(pickFrom(['W', 'M', 'U'])),
    productsubcategoryid: structuralDefault,
    productmodelid: structuralDefault,
    sellstartdate: timestampBetween('2011-01-01', '2020-12-31'),
    sellenddate: constant(null),
    discontinueddate: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productcategoryInProduction: {
    productcategoryid: structuralDefault,
    name: fromList(PRODUCT_CATEGORIES),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productcosthistoryInProduction: {
    productid: structuralDefault,
    startdate: timestampBetween('2011-01-01', '2023-12-31'),
    enddate: constant(null),
    standardcost: randomDecimalString(1, 1500, 2),
    modifieddate: structuralDefault,
  },
  productdescriptionInProduction: {
    productdescriptionid: structuralDefault,
    description: derive(() => faker.commerce.productDescription().slice(0, 400)),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productdocumentInProduction: {
    productid: structuralDefault,
    modifieddate: structuralDefault,
    documentnode: derive((_row, context) => `/doc${context.rowIndex % DOCUMENT_TITLES.length}/`),
  },
  productinventoryInProduction: {
    productid: structuralDefault,
    locationid: structuralDefault,
    shelf: pickFrom(['A', 'B', 'C', 'D', 'E']),
    bin: randomInteger(0, 100),
    quantity: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productlistpricehistoryInProduction: {
    productid: structuralDefault,
    startdate: timestampBetween('2011-01-01', '2023-12-31'),
    enddate: constant(null),
    listprice: randomDecimalString(1, 3500, 2),
    modifieddate: structuralDefault,
  },
  productmodelInProduction: {
    productmodelid: structuralDefault,
    name: fromList(PRODUCT_MODELS),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productmodelillustrationInProduction: {
    productmodelid: structuralDefault,
    illustrationid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productmodelproductdescriptioncultureInProduction: {
    productmodelid: structuralDefault,
    productdescriptionid: structuralDefault,
    cultureid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productphotoInProduction: {
    productphotoid: structuralDefault,
    thumbnailphotofilename: derive((_row, context) => `product_${context.rowIndex + 1}_small.gif`),
    largephotofilename: derive((_row, context) => `product_${context.rowIndex + 1}_large.gif`),
    modifieddate: structuralDefault,
  },
  productproductphotoInProduction: {
    productid: structuralDefault,
    productphotoid: structuralDefault,
    primary: structuralDefault,
    modifieddate: structuralDefault,
  },
  productreviewInProduction: {
    productreviewid: structuralDefault,
    productid: structuralDefault,
    reviewername: derive(() => faker.person.fullName().slice(0, 50)),
    reviewdate: structuralDefault,
    emailaddress: emailAddress(),
    rating: randomInteger(1, 5),
    comments: optional(derive(() => faker.lorem.sentences(2))),
    modifieddate: structuralDefault,
  },
  productsubcategoryInProduction: {
    productsubcategoryid: structuralDefault,
    // Categories are generated first and numbered from one, so a subcategory can name its own
    // parent rather than taking whichever the pool offers: mountain bikes sit under bikes.
    productcategoryid: derive((_row, context) => PRODUCT_SUBCATEGORIES[context.rowIndex][1] + 1),
    name: derive((_row, context) => PRODUCT_SUBCATEGORIES[context.rowIndex][0]),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  productvendorInPurchasing: {
    productid: structuralDefault,
    businessentityid: randomInteger(1001, 1300),
    averageleadtime: randomInteger(1, 60),
    standardprice: randomDecimalString(1, 200, 2),
    lastreceiptcost: optional(randomDecimalString(1, 200, 2)),
    lastreceiptdate: structuralDefault,
    minorderqty: randomInteger(1, 10),
    maxorderqty: randomInteger(10, 1000),
    onorderqty: optional(randomInteger(0, 500)),
    unitmeasurecode: structuralDefault,
    modifieddate: structuralDefault,
  },
  purchaseorderdetailInPurchasing: {
    purchaseorderid: structuralDefault,
    purchaseorderdetailid: structuralDefault,
    duedate: timestampBetween('2012-01-01', '2025-12-31'),
    orderqty: randomInteger(1, 500),
    productid: structuralDefault,
    unitprice: randomDecimalString(0, 200, 2),
    receivedqty: randomDecimalString(0, 500, 2),
    rejectedqty: randomDecimalString(0, 10, 2),
    modifieddate: structuralDefault,
  },
  purchaseorderheaderInPurchasing: {
    purchaseorderid: structuralDefault,
    revisionnumber: structuralDefault,
    status: randomInteger(1, 4),
    employeeid: structuralDefault,
    vendorid: structuralDefault,
    shipmethodid: structuralDefault,
    orderdate: timestampBetween('2012-01-01', '2024-12-31'),
    shipdate: derive((row) => plusDays(String(row.orderdate), 10)),
    subtotal: randomDecimalString(0, 20000, 2),
    taxamt: randomDecimalString(0, 1600, 2),
    freight: randomDecimalString(0, 500, 2),
    modifieddate: structuralDefault,
  },
  salesorderdetailInSales: {
    salesorderid: structuralDefault,
    salesorderdetailid: structuralDefault,
    carriertrackingnumber: structuralDefault,
    orderqty: randomInteger(1, 12),
    productid: randomInteger(1, 500),
    specialofferid: constant(1),
    unitprice: randomDecimalString(1, 3500, 2),
    unitpricediscount: constant('0.00'),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesorderheaderInSales: {
    salesorderid: structuralDefault,
    revisionnumber: structuralDefault,
    orderdate: timestampBetween('2012-01-01', '2024-12-31'),
    duedate: derive((row) => plusDays(String(row.orderdate), 12)),
    shipdate: derive((row) => plusDays(String(row.orderdate), 7)),
    status: randomInteger(0, 8),
    onlineorderflag: structuralDefault,
    purchaseordernumber: structuralDefault,
    accountnumber: structuralDefault,
    customerid: structuralDefault,
    salespersonid: structuralDefault,
    territoryid: structuralDefault,
    billtoaddressid: structuralDefault,
    shiptoaddressid: structuralDefault,
    shipmethodid: structuralDefault,
    creditcardid: structuralDefault,
    creditcardapprovalcode: optional(randomWords({ minLength: 10, maxLength: 15 })),
    currencyrateid: structuralDefault,
    subtotal: randomDecimalString(0, 20000, 2),
    taxamt: randomDecimalString(0, 1600, 2),
    freight: randomDecimalString(0, 500, 2),
    totaldue: structuralDefault,
    comment: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesorderheadersalesreasonInSales: {
    salesorderid: structuralDefault,
    salesreasonid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salespersonInSales: {
    businessentityid: rowNumber,
    territoryid: structuralDefault,
    salesquota: optional(randomDecimalString(100000, 300000, 2)),
    bonus: randomDecimalString(0, 6000, 2),
    commissionpct: randomDecimalString(0, 0.02, 4),
    salesytd: randomDecimalString(0, 4000000, 2),
    saleslastyear: randomDecimalString(0, 4000000, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salespersonquotahistoryInSales: {
    businessentityid: randomInteger(1, 17),
    quotadate: timestampBetween('2012-01-01', '2024-12-31'),
    salesquota: randomDecimalString(100000, 300000, 2),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesreasonInSales: {
    salesreasonid: structuralDefault,
    name: derive((_row, context) => SALES_REASONS[context.rowIndex][0]),
    reasontype: derive((_row, context) => SALES_REASONS[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  salestaxrateInSales: {
    salestaxrateid: structuralDefault,
    stateprovinceid: structuralDefault,
    taxtype: randomInteger(1, 3),
    taxrate: randomDecimalString(0, 20, 2),
    name: properName(),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesterritoryInSales: {
    territoryid: structuralDefault,
    name: derive((_row, context) => SALES_TERRITORIES[context.rowIndex][0]),
    countryregioncode: derive((_row, context) => SALES_TERRITORIES[context.rowIndex][1]),
    group: derive((_row, context) => SALES_TERRITORIES[context.rowIndex][2]),
    salesytd: randomDecimalString(0, 8000000, 2),
    saleslastyear: randomDecimalString(0, 8000000, 2),
    costytd: constant('0.00'),
    costlastyear: constant('0.00'),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  salesterritoryhistoryInSales: {
    businessentityid: rowNumber,
    territoryid: structuralDefault,
    startdate: timestampBetween('2012-01-01', '2020-12-31'),
    enddate: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  scrapreasonInProduction: {
    scrapreasonid: structuralDefault,
    name: fromList(SCRAP_REASONS),
    modifieddate: structuralDefault,
  },
  shiftInHumanresources: {
    shiftid: structuralDefault,
    name: derive((_row, context) => SHIFTS[context.rowIndex][0]),
    starttime: derive((_row, context) => SHIFTS[context.rowIndex][1]),
    endtime: derive((_row, context) => SHIFTS[context.rowIndex][2]),
    modifieddate: structuralDefault,
  },
  shipmethodInPurchasing: {
    shipmethodid: structuralDefault,
    name: derive((_row, context) => SHIP_METHODS[context.rowIndex][0]),
    shipbase: derive((_row, context) => SHIP_METHODS[context.rowIndex][1]),
    shiprate: derive((_row, context) => SHIP_METHODS[context.rowIndex][2]),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  shoppingcartitemInSales: {
    shoppingcartitemid: structuralDefault,
    shoppingcartid: derive((_row, context) => `cart-${String(context.rowIndex + 1).padStart(6, '0')}`),
    quantity: randomInteger(1, 6),
    productid: structuralDefault,
    datecreated: structuralDefault,
    modifieddate: structuralDefault,
  },
  specialofferInSales: {
    specialofferid: structuralDefault,
    description: derive((_row, context) => SPECIAL_OFFERS[context.rowIndex][0]),
    discountpct: derive((_row, context) => SPECIAL_OFFERS[context.rowIndex][3]),
    type: derive((_row, context) => SPECIAL_OFFERS[context.rowIndex][1]),
    category: derive((_row, context) => SPECIAL_OFFERS[context.rowIndex][2]),
    startdate: timestampBetween('2012-01-01', '2020-12-31'),
    enddate: derive((row) => plusDays(String(row.startdate), 365)),
    minqty: randomInteger(0, 4),
    maxqty: constant(null),
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  specialofferproductInSales: {
    specialofferid: constant(1),
    productid: rowNumber,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  stateprovinceInPerson: {
    stateprovinceid: structuralDefault,
    stateprovincecode: derive((_row, context) => STATE_PROVINCES[context.rowIndex][0]),
    // The country each state belongs to, so the pair reads correctly rather than being two
    // independent picks; every code here exists in COUNTRY_REGIONS.
    countryregioncode: derive((_row, context) => STATE_PROVINCES[context.rowIndex][2]),
    isonlystateprovinceflag: constant(false),
    name: derive((_row, context) => STATE_PROVINCES[context.rowIndex][1]),
    territoryid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  storeInSales: {
    businessentityid: derive((_row, context) => PERSONS + VENDORS + context.rowIndex + 1),
    // Bicycle retailers, which is what an AdventureWorks store is.
    name: derive(() => `${faker.company.name()} Cycles`.slice(0, 50)),
    salespersonid: structuralDefault,
    rowguid: structuralDefault,
    modifieddate: structuralDefault,
  },
  transactionhistoryInProduction: {
    transactionid: structuralDefault,
    productid: structuralDefault,
    referenceorderid: structuralDefault,
    referenceorderlineid: structuralDefault,
    transactiondate: structuralDefault,
    transactiontype: pickFrom(['W', 'S', 'P']),
    quantity: structuralDefault,
    actualcost: structuralDefault,
    modifieddate: structuralDefault,
  },
  transactionhistoryarchiveInProduction: {
    transactionid: structuralDefault,
    productid: structuralDefault,
    referenceorderid: structuralDefault,
    referenceorderlineid: structuralDefault,
    transactiondate: structuralDefault,
    transactiontype: pickFrom(['W', 'S', 'P']),
    quantity: structuralDefault,
    actualcost: structuralDefault,
    modifieddate: structuralDefault,
  },
  unitmeasureInProduction: {
    unitmeasurecode: derive((_row, context) => UNIT_MEASURES[context.rowIndex][0]),
    name: derive((_row, context) => UNIT_MEASURES[context.rowIndex][1]),
    modifieddate: structuralDefault,
  },
  vendorInPurchasing: {
    businessentityid: derive((_row, context) => PERSONS + context.rowIndex + 1),
    accountnumber: derive((_row, context) => `VENDOR${String(context.rowIndex).padStart(7, '0')}`),
    name: derive(() => faker.company.name().slice(0, 50)),
    creditrating: randomInteger(1, 5),
    preferredvendorstatus: structuralDefault,
    activeflag: structuralDefault,
    purchasingwebserviceurl: optional(derive(() => `https://www.${faker.internet.domainWord()}.com/purchasing`)),
    modifieddate: structuralDefault,
  },
  workorderInProduction: {
    workorderid: structuralDefault,
    productid: structuralDefault,
    orderqty: randomInteger(1, 60),
    scrappedqty: randomInteger(0, 5),
    startdate: timestampBetween('2012-01-01', '2024-12-31'),
    enddate: constant(null),
    duedate: structuralDefault,
    scrapreasonid: structuralDefault,
    modifieddate: structuralDefault,
  },
  workorderroutingInProduction: {
    workorderid: structuralDefault,
    productid: structuralDefault,
    operationsequence: structuralDefault,
    locationid: structuralDefault,
    scheduledstartdate: timestampBetween('2012-01-01', '2024-12-31'),
    scheduledenddate: derive((row) => plusDays(String(row.scheduledstartdate), 14)),
    actualstartdate: constant(null),
    actualenddate: constant(null),
    actualresourcehrs: constant(null),
    plannedcost: randomDecimalString(1, 200, 2),
    actualcost: constant(null),
    modifieddate: structuralDefault,
  },
} satisfies SchemaRules<typeof schema>;
